In [1]:
import tensorflow as tf

C:\Users\Delanoue\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


First Graph

In [2]:
x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x*x*y + y +2


In [3]:
sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)


In [4]:
result

42

In [5]:
sess.close()

Knack

In [6]:
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    result = f.eval()

In [7]:
result

42

In [11]:
import numpy as np
from sklearn.datasets import fetch_california_housing

In [13]:
housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m,1)),housing.data]


downloading Cal. housing from http://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.tgz to C:\Users\Delanoue\scikit_learn_data


In [15]:
X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1,1), dtype=tf.float32, name="y")
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)),XT),y)

In [16]:
with tf.Session() as sess:
    theta_value = theta.eval()

In [17]:
theta_value


array([[-3.7185181e+01],
       [ 4.3633747e-01],
       [ 9.3952334e-03],
       [-1.0711310e-01],
       [ 6.4479220e-01],
       [-4.0338000e-06],
       [-3.7813708e-03],
       [-4.2348403e-01],
       [-4.3721911e-01]], dtype=float32)

Feeding Data to the training Algorithm 

Placeholder node 

In [26]:
A = tf.placeholder(tf.float32, shape=(None,None))
B= A+5
with tf.Session() as sess :
    B_val_1 = B.eval(feed_dict={A: [[1, 2, 3,4]]})
    B_val_2 = B.eval(feed_dict={A: [[4, 5, 6], [7, 8, 9]]})

In [27]:
B_val_2

array([[ 9., 10., 11.],
       [12., 13., 14.]], dtype=float32)

In [28]:
B_val_1

array([[6., 7., 8., 9.]], dtype=float32)

# Saving and Restoring Models

In [29]:
import tensorboard as tb